CREATE TABLE SONG(
  ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR(100),
  ARTIST VARCHAR(100),
  ALBUM VARCHAR(100),
  LENGTH_SEC INTEGER,
  RESOURCE_ID BIGINT,
  YEAR SMALLINT
);

CREATE SEQUENCE SONG_SEQ;

ALTER SEQUENCE SONG_SEQ RESTART WITH 100;